# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b71bab37c8c2731aa2959f42be25287183ce8030903b6604c219da5ca099ba2a026ecc260937485e6c5588379d1178ac2f2a20fd8c3aa11410c4392830d1cf

test:
  secret_key_base: 056aab5f90a56464a211d12904e62e52559187dda8ad0f334f07c079d83349a52e1a4b658447c6f9d4b0e37ae22edc21fdb1c6b20722299a121680fce2b0c067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
